// Auto-generated by update-index.js. Do not edit directly.
window.REPO_FILES = [
  {
    "name": "app-release.apk",
    "path": "app-release.apk",
    "folder": "Root",
    "size": 11576833,
    "lastModified": "2026-10-05T19:00:44.378Z"
  },
  {
    "name": "module.zip",
    "path": "module.zip",
    "folder": "Root",
    "size": 99758,
    "lastModified": "2026-10-01T19:23:51.500Z"
  },
  {
    "name": "sock64",
    "path": "sock64",
    "folder": "Root",
    "size": 737464,
    "lastModified": "2026-10-05T19:02:12.914Z"
  },
  {
    "name": "wanbai.kpm",
    "path": "wanbai.kpm",
    "folder": "Root",
    "size": 26008,
    "lastModified": "2026-10-01T19:15:57.429Z"
  },
  {
    "name": "4.14.117.ko",
    "path": "QX-Drivers/4.14.117.ko",
    "folder": "QX-Drivers",
    "size": 526184,
    "lastModified": "2026-10-04T19:40:25.515Z"
  },
  {
    "name": "4.14.141.ko",
    "path": "QX-Drivers/4.14.141.ko",
    "folder": "QX-Drivers",
    "size": 529768,
    "lastModified": "2026-10-04T19:40:25.517Z"
  },
  {
    "name": "4.14.180.ko",
    "path": "QX-Drivers/4.14.180.ko",
    "folder": "QX-Drivers",
    "size": 538040,
    "lastModified": "2026-10-04T19:40:25.520Z"
  },
  {
    "name": "4.14.186.ko",
    "path": "QX-Drivers/4.14.186.ko",
    "folder": "QX-Drivers",
    "size": 535632,
    "lastModified": "2026-10-04T19:40:25.521Z"
  },
  {
    "name": "4.14.186b.ko",
    "path": "QX-Drivers/4.14.186b.ko",
    "folder": "QX-Drivers",
    "size": 533384,
    "lastModified": "2026-10-04T19:40:25.522Z"
  },
  {
    "name": "4.14.186c.ko",
    "path": "QX-Drivers/4.14.186c.ko",
    "folder": "QX-Drivers",
    "size": 535384,
    "lastModified": "2026-10-04T19:40:25.523Z"
  },
  {
    "name": "4.19.113.ko",
    "path": "QX-Drivers/4.19.113.ko",
    "folder": "QX-Drivers",
    "size": 561304,
    "lastModified": "2026-10-04T19:40:25.524Z"
  },
  {
    "name": "4.19.157.ko",
    "path": "QX-Drivers/4.19.157.ko",
    "folder": "QX-Drivers",
    "size": 572208,
    "lastModified": "2026-10-04T19:40:25.525Z"
  },
  {
    "name": "4.19.157b.ko",
    "path": "QX-Drivers/4.19.157b.ko",
    "folder": "QX-Drivers",
    "size": 665536,
    "lastModified": "2026-10-04T19:40:25.526Z"
  },
  {
    "name": "4.19.157c.ko",
    "path": "QX-Drivers/4.19.157c.ko",
    "folder": "QX-Drivers",
    "size": 654056,
    "lastModified": "2026-10-04T19:40:25.528Z"
  },
  {
    "name": "4.19.191.ko",
    "path": "QX-Drivers/4.19.191.ko",
    "folder": "QX-Drivers",
    "size": 674616,
    "lastModified": "2026-10-04T19:40:25.529Z"
  },
  {
    "name": "4.19.191b.ko",
    "path": "QX-Drivers/4.19.191b.ko",
    "folder": "QX-Drivers",
    "size": 680976,
    "lastModified": "2026-10-04T19:40:25.530Z"
  },
  {
    "name": "4.19.191c.ko",
    "path": "QX-Drivers/4.19.191c.ko",
    "folder": "QX-Drivers",
    "size": 674792,
    "lastModified": "2026-10-04T19:40:25.531Z"
  },
  {
    "name": "4.19.81.ko",
    "path": "QX-Drivers/4.19.81.ko",
    "folder": "QX-Drivers",
    "size": 550680,
    "lastModified": "2026-10-04T19:40:25.533Z"
  },
  {
    "name": "5.10-Pixel.ko",
    "path": "QX-Drivers/5.10-Pixel.ko",
    "folder": "QX-Drivers",
    "size": 343336,
    "lastModified": "2026-10-05T18:13:12.729Z"
  },
  {
    "name": "5.10.ko",
    "path": "QX-Drivers/5.10.ko",
    "folder": "QX-Drivers",
    "size": 1036200,
    "lastModified": "2026-10-04T19:40:25.535Z"
  },
  {
    "name": "5.10b.ko",
    "path": "QX-Drivers/5.10b.ko",
    "folder": "QX-Drivers",
    "size": 343232,
    "lastModified": "2026-10-05T18:13:12.731Z"
  },
  {
    "name": "5.15.ko",
    "path": "QX-Drivers/5.15.ko",
    "folder": "QX-Drivers",
    "size": 1050400,
    "lastModified": "2026-10-04T19:40:25.537Z"
  },
  {
    "name": "5.4.ko",
    "path": "QX-Drivers/5.4.ko",
    "folder": "QX-Drivers",
    "size": 861384,
    "lastModified": "2026-10-04T19:40:25.539Z"
  },
  {
    "name": "5.4b.ko",
    "path": "QX-Drivers/5.4b.ko",
    "folder": "QX-Drivers",
    "size": 854808,
    "lastModified": "2026-10-04T19:40:25.540Z"
  },
  {
    "name": "5.4c.ko",
    "path": "QX-Drivers/5.4c.ko",
    "folder": "QX-Drivers",
    "size": 862128,
    "lastModified": "2026-10-04T19:40:25.542Z"
  },
  {
    "name": "6.1.ko",
    "path": "QX-Drivers/6.1.ko",
    "folder": "QX-Drivers",
    "size": 983760,
    "lastModified": "2026-10-04T19:40:25.544Z"
  },
  {
    "name": "6.12.23.ko",
    "path": "QX-Drivers/6.12.23.ko",
    "folder": "QX-Drivers",
    "size": 693592,
    "lastModified": "2026-10-04T19:40:25.545Z"
  },
  {
    "name": "6.12.58.ko",
    "path": "QX-Drivers/6.12.58.ko",
    "folder": "QX-Drivers",
    "size": 741392,
    "lastModified": "2026-10-04T19:40:25.546Z"
  },
  {
    "name": "6.6.ko",
    "path": "QX-Drivers/6.6.ko",
    "folder": "QX-Drivers",
    "size": 787024,
    "lastModified": "2026-10-04T19:40:25.548Z"
  },
  {
    "name": "4.14.117.ko",
    "path": "RT-Drivers/4.14.117.ko",
    "folder": "RT-Drivers",
    "size": 169704,
    "lastModified": "2026-10-01T19:15:57.413Z"
  },
  {
    "name": "4.14.180.ko",
    "path": "RT-Drivers/4.14.180.ko",
    "folder": "RT-Drivers",
    "size": 170984,
    "lastModified": "2026-10-01T19:15:57.413Z"
  },
  {
    "name": "4.14.186.ko",
    "path": "RT-Drivers/4.14.186.ko",
    "folder": "RT-Drivers",
    "size": 169392,
    "lastModified": "2026-10-01T19:15:57.417Z"
  },
  {
    "name": "4.19.113.ko",
    "path": "RT-Drivers/4.19.113.ko",
    "folder": "RT-Drivers",
    "size": 179520,
    "lastModified": "2026-10-01T19:15:57.417Z"
  },
  {
    "name": "4.19.157-ColorOS.ko",
    "path": "RT-Drivers/4.19.157-ColorOS.ko",
    "folder": "RT-Drivers",
    "size": 182912,
    "lastModified": "2026-10-01T19:15:57.419Z"
  },
  {
    "name": "4.19.157.ko",
    "path": "RT-Drivers/4.19.157.ko",
    "folder": "RT-Drivers",
    "size": 183408,
    "lastModified": "2026-10-01T19:15:57.419Z"
  },
  {
    "name": "4.19.191-ColorOS.ko",
    "path": "RT-Drivers/4.19.191-ColorOS.ko",
    "folder": "RT-Drivers",
    "size": 211784,
    "lastModified": "2026-10-01T19:15:57.419Z"
  },
  {
    "name": "4.19.81.ko",
    "path": "RT-Drivers/4.19.81.ko",
    "folder": "RT-Drivers",
    "size": 175328,
    "lastModified": "2026-10-01T19:15:57.419Z"
  },
  {
    "name": "4.9.186.ko",
    "path": "RT-Drivers/4.9.186.ko",
    "folder": "RT-Drivers",
    "size": 207576,
    "lastModified": "2026-10-01T19:15:57.419Z"
  },
  {
    "name": "5.10.ko",
    "path": "RT-Drivers/5.10.ko",
    "folder": "RT-Drivers",
    "size": 389896,
    "lastModified": "2026-10-01T19:15:57.419Z"
  },
  {
    "name": "5.15.ko",
    "path": "RT-Drivers/5.15.ko",
    "folder": "RT-Drivers",
    "size": 397304,
    "lastModified": "2026-10-01T19:15:57.429Z"
  },
  {
    "name": "5.4-ColorOS.ko",
    "path": "RT-Drivers/5.4-ColorOS.ko",
    "folder": "RT-Drivers",
    "size": 301216,
    "lastModified": "2026-10-01T19:15:57.429Z"
  },
  {
    "name": "5.4.236.ko",
    "path": "RT-Drivers/5.4.236.ko",
    "folder": "RT-Drivers",
    "size": 317304,
    "lastModified": "2026-10-01T19:15:57.429Z"
  },
  {
    "name": "6.1.ko",
    "path": "RT-Drivers/6.1.ko",
    "folder": "RT-Drivers",
    "size": 391736,
    "lastModified": "2026-10-01T19:15:57.429Z"
  },
  {
    "name": "6.6.ko",
    "path": "RT-Drivers/6.6.ko",
    "folder": "RT-Drivers",
    "size": 327560,
    "lastModified": "2026-10-01T16:39:13.000Z"
  },
  {
    "name": "note12pro.ko",
    "path": "RT-Drivers/note12pro.ko",
    "folder": "RT-Drivers",
    "size": 187096,
    "lastModified": "2026-10-01T19:15:57.429Z"
  },
  {
    "name": "4.14.186-perf-g43464e2eb858.ko",
    "path": "ZL-Drivers/4.14.186-perf-g43464e2eb858.ko",
    "folder": "ZL-Drivers",
    "size": 331104,
    "lastModified": "2026-10-01T19:15:57.333Z"
  },
  {
    "name": "4.19.113.ko",
    "path": "ZL-Drivers/4.19.113.ko",
    "folder": "ZL-Drivers",
    "size": 424000,
    "lastModified": "2026-10-01T19:15:57.333Z"
  },
  {
    "name": "5.10.ko",
    "path": "ZL-Drivers/5.10.ko",
    "folder": "ZL-Drivers",
    "size": 568376,
    "lastModified": "2026-10-01T19:15:57.333Z"
  },
  {
    "name": "5.15.ko",
    "path": "ZL-Drivers/5.15.ko",
    "folder": "ZL-Drivers",
    "size": 573160,
    "lastModified": "2026-10-01T19:15:57.346Z"
  },
  {
    "name": "6.1.ko",
    "path": "ZL-Drivers/6.1.ko",
    "folder": "ZL-Drivers",
    "size": 519576,
    "lastModified": "2026-10-01T19:15:57.349Z"
  },
  {
    "name": "6.12.ko",
    "path": "ZL-Drivers/6.12.ko",
    "folder": "ZL-Drivers",
    "size": 368392,
    "lastModified": "2026-10-01T19:15:57.351Z"
  },
  {
    "name": "6.6.ko",
    "path": "ZL-Drivers/6.6.ko",
    "folder": "ZL-Drivers",
    "size": 337160,
    "lastModified": "2026-10-02T18:56:54.647Z"
  }
];
