const fs = require('fs');
const path = require('path');

// Target directory to scan (current directory)
const rootDir = __dirname;
const outputFile = path.join(rootDir, 'files-data.js');

// List of filenames or directories to ignore
const ignoreList = new Set([
  '.git',
  '.github',
  'node_modules',
  'index.html',
  'style.css',
  'app.js',
  'files-data.js',
  'update-index.js',
  '.gitignore',
  'README.md'
]);

function getFilesRecursively(dir, relativePath = '') {
  let results = [];
  const list = fs.readdirSync(dir);

  list.forEach((file) => {
    const filePath = path.join(dir, file);
    const relFilePath = relativePath ? path.join(relativePath, file) : file;
    
    // Normalize path separators to forward slashes for URLs
    const normalizedRelPath = relFilePath.replace(/\\/g, '/');

    // Skip ignored items
    if (ignoreList.has(file) || ignoreList.has(normalizedRelPath)) {
      return;
    }

    const stat = fs.statSync(filePath);
    if (stat.isDirectory()) {
      results = results.concat(getFilesRecursively(filePath, relFilePath));
    } else {
      // Determine logical category/folder
      let folderName = 'Root';
      if (normalizedRelPath.includes('/')) {
        folderName = normalizedRelPath.split('/')[0];
      }

      results.push({
        name: file,
        path: normalizedRelPath,
        folder: folderName,
        size: stat.size,
        lastModified: stat.mtime
      });
    }
  });

  return results;
}

try {
  console.log('Scanning workspace for files...');
  const filesList = getFilesRecursively(rootDir);
  
  // Sort files: Root files first, then QX-Drivers, then RT-Drivers, etc.
  // Within folders, sort alphabetically by name.
  filesList.sort((a, b) => {
    if (a.folder === 'Root' && b.folder !== 'Root') return -1;
    if (a.folder !== 'Root' && b.folder === 'Root') return 1;
    if (a.folder !== b.folder) return a.folder.localeCompare(b.folder);
    return a.name.localeCompare(b.name);
  });

  const outputContent = `// Auto-generated by update-index.js. Do not edit directly.\nwindow.REPO_FILES = ${JSON.stringify(filesList, null, 2)};\n`;
  
  fs.writeFileSync(outputFile, outputContent, 'utf-8');
  console.log(`Successfully indexed ${filesList.length} files and wrote output to: files-data.js`);
} catch (error) {
  console.error('Error generating file index:', error);
  process.exit(1);
}
